// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RequestManagement.Server.Data;

#nullable disable

namespace RequestManagement.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250506123528_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RequestManagement.Common.Models.Commissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproveForActId")
                        .HasColumnType("integer");

                    b.Property<int>("ApproveForDefectAndLimitId")
                        .HasColumnType("integer");

                    b.Property<int>("ChairmanId")
                        .HasColumnType("integer");

                    b.Property<int>("Member1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Member2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Member3Id")
                        .HasColumnType("integer");

                    b.Property<int>("Member4Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApproveForActId");

                    b.HasIndex("ApproveForDefectAndLimitId");

                    b.HasIndex("ChairmanId");

                    b.HasIndex("Member1Id");

                    b.HasIndex("Member2Id");

                    b.HasIndex("Member3Id");

                    b.HasIndex("Member4Id");

                    b.ToTable("Commissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApproveForActId = 1,
                            ApproveForDefectAndLimitId = 1,
                            ChairmanId = 1,
                            Member1Id = 1,
                            Member2Id = 1,
                            Member3Id = 1,
                            Member4Id = 1,
                            Name = "Магический филиал"
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Defect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefectGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefectGroupId");

                    b.ToTable("Defects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefectGroupId = 1,
                            Name = "Трещина корпуса"
                        },
                        new
                        {
                            Id = 2,
                            DefectGroupId = 2,
                            Name = "Короткое замыкание"
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.DefectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DefectGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Механические повреждения"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Электрические неисправности"
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "",
                            FullName = "",
                            Position = "",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 2,
                            Code = "",
                            FullName = "Петров Петр Петрович",
                            Position = "Водитель",
                            ShortName = "Петров П.П."
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "",
                            Name = "КАМАЗ 53215-15",
                            StateNumber = "Н 507 СН"
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefectId")
                        .HasColumnType("integer");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.HasIndex("DriverId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("StockId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "",
                            Date = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefectId = 1,
                            DriverId = 1,
                            EquipmentId = 1,
                            Quantity = 5m,
                            StockId = 1
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Incoming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Incoming");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 5m,
                            StockId = 1
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Nomenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Nomenclature");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Article = "7406.1118013",
                            Code = "ТКР001",
                            Name = "Турбокомпрессор ТКР 7С-6 левый КАМАЗ Евро 2",
                            UnitOfMeasure = "шт"
                        },
                        new
                        {
                            Id = 2,
                            Article = "6СТ-190",
                            Code = "АКБ001",
                            Name = "Аккумулятор 6СТ-190",
                            UnitOfMeasure = "шт"
                        },
                        new
                        {
                            Id = 3,
                            Article = "6СТ-200",
                            Code = "АКБ002",
                            Name = "Аккумулятор 6СТ-200 (аналог 6СТ-190)",
                            UnitOfMeasure = "шт"
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.NomenclatureDefectMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("UserId");

                    b.ToTable("NomenclatureDefectMappings");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumedQuantity = 0m,
                            InitialQuantity = 70m,
                            NomenclatureId = 1,
                            ReceivedQuantity = 0m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConsumedQuantity = 0m,
                            InitialQuantity = 10m,
                            NomenclatureId = 2,
                            ReceivedQuantity = 0m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            ConsumedQuantity = 0m,
                            InitialQuantity = 40m,
                            NomenclatureId = 1,
                            ReceivedQuantity = 0m,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            ConsumedQuantity = 0m,
                            InitialQuantity = 20m,
                            NomenclatureId = 2,
                            ReceivedQuantity = 0m,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "$2a$11$IeKuyvG/5SoDYP0NFz3kouC3CPUIuUa6ShTfgVVf9oUlfqbXq8LrC",
                            Role = 0
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.UserLastSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommissionsId")
                        .HasColumnType("integer");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommissionsId");

                    b.HasIndex("DriverId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLastSelections");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "",
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Основной склад"
                        },
                        new
                        {
                            Id = 2,
                            Code = "",
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Резервный склад"
                        });
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Commissions", b =>
                {
                    b.HasOne("RequestManagement.Common.Models.Driver", "ApproveForAct")
                        .WithMany()
                        .HasForeignKey("ApproveForActId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.Common.Models.Driver", "ApproveForDefectAndLimit")
                        .WithMany()
                        .HasForeignKey("ApproveForDefectAndLimitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.Common.Models.Driver", "Chairman")
                        .WithMany()
                        .HasForeignKey("ChairmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.Common.Models.Driver", "Member1")
                        .WithMany()
                        .HasForeignKey("Member1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.Common.Models.Driver", "Member2")
                        .WithMany()
                        .HasForeignKey("Member2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.Common.Models.Driver", "Member3")
                        .WithMany()
                        .HasForeignKey("Member3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RequestManagement.Common.Models.Driver", "Member4")
                        .WithMany()
                        .HasForeignKey("Member4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApproveForAct");

                    b.Navigation("ApproveForDefectAndLimit");

                    b.Navigation("Chairman");

                    b.Navigation("Member1");

                    b.Navigation("Member2");

                    b.Navigation("Member3");

                    b.Navigation("Member4");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Defect", b =>
                {
                    b.HasOne("RequestManagement.Common.Models.DefectGroup", "DefectGroup")
                        .WithMany("Defects")
                        .HasForeignKey("DefectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectGroup");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Expense", b =>
                {
                    b.HasOne("RequestManagement.Common.Models.Defect", "Defect")
                        .WithMany()
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestManagement.Common.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestManagement.Common.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestManagement.Common.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Defect");

                    b.Navigation("Driver");

                    b.Navigation("Equipment");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Incoming", b =>
                {
                    b.HasOne("RequestManagement.Common.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.NomenclatureDefectMapping", b =>
                {
                    b.HasOne("RequestManagement.Common.Models.Defect", "Defect")
                        .WithMany()
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestManagement.Common.Models.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestManagement.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defect");

                    b.Navigation("Nomenclature");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Stock", b =>
                {
                    b.HasOne("RequestManagement.Common.Models.Nomenclature", "Nomenclature")
                        .WithMany("Stocks")
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestManagement.Common.Models.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.UserLastSelection", b =>
                {
                    b.HasOne("RequestManagement.Common.Models.Commissions", "Commissions")
                        .WithMany()
                        .HasForeignKey("CommissionsId");

                    b.HasOne("RequestManagement.Common.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("RequestManagement.Common.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.HasOne("RequestManagement.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commissions");

                    b.Navigation("Driver");

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.DefectGroup", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Nomenclature", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("RequestManagement.Common.Models.Warehouse", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
